# Collect exact upstream notices from the pinned dependency checkouts.
set(PMX_NOTICES_DIR "${CMAKE_BINARY_DIR}/distribution/licenses")
file(MAKE_DIRECTORY "${PMX_NOTICES_DIR}")
file(COPY "${CMAKE_SOURCE_DIR}/LICENSE" "${CMAKE_SOURCE_DIR}/NOTICE.txt" "${CMAKE_SOURCE_DIR}/SOURCE.md" DESTINATION "${PMX_NOTICES_DIR}")
file(COPY "${CMAKE_SOURCE_DIR}/docs/licenses/" DESTINATION "${PMX_NOTICES_DIR}/additional")
foreach(root IN ITEMS "${juce_SOURCE_DIR}" "${namcore_SOURCE_DIR}")
    if(EXISTS "${root}")
        get_filename_component(label "${root}" NAME)
        file(GLOB_RECURSE notices LIST_DIRECTORIES FALSE "${root}/LICENSE*" "${root}/COPYING*")
        foreach(notice IN LISTS notices)
            if(notice MATCHES "/\\.git/")
                continue()
            endif()
            file(RELATIVE_PATH relative "${root}" "${notice}")
            get_filename_component(parent "${relative}" DIRECTORY)
            file(MAKE_DIRECTORY "${PMX_NOTICES_DIR}/${label}/${parent}")
            file(COPY "${notice}" DESTINATION "${PMX_NOTICES_DIR}/${label}/${parent}")
        endforeach()
    endif()
endforeach()
if(EXISTS "${juce_SOURCE_DIR}/JUCE.spdx.json")
    file(COPY "${juce_SOURCE_DIR}/JUCE.spdx.json" DESTINATION "${PMX_NOTICES_DIR}")
endif()

